export const products = [
    {
        id: 1,
        name: '#1',
        sku: 'SKU001',
        category: '-',
        stock: 100,
        price: '$10.00',
        status: 'Published',
        added: '2024-01-01',
        image: 'path_to_product_image1',
        variants: ['Variant 1', 'Variant 2']
    },
    {
        id: 2,
        name: '#2',
        sku: 'SKU002',
        category: '-',
        stock: 50,
        price: '$20.00',
        status: 'Low Stock',
        added: '2024-02-15',
        image: 'path_to_product_image2',
        variants: ['Variant 1', 'Variant 3']
    },
    {
        id: 3,
        name: '#3',
        sku: 'SKU003',
        category: '-',
        stock: 200,
        price: '$15.00',
        status: 'Out of Stock',
        added: '2024-03-10',
        image: 'path_to_product_image3',
        variants: ['Variant 2', 'Variant 3']
    },
    {
        id: 4,
        name: '#4',
        sku: 'SKU004',
        category: '-',
        stock: 200,
        price: '$15.00',
        status: 'Draft',
        added: '2024-03-10',
        image: 'path_to_product_image3',
        variants: ['Variant 2', 'Variant 3']
    },
    {
        id: 5,
        name: '#5',
        sku: 'SKU004',
        category: '-',
        stock: 200,
        price: '$15.00',
        status: 'Draft',
        added: '2024-03-10',
        image: 'path_to_product_image3',
        variants: ['Variant 2', 'Variant 3']
    },
    {
        id: 6,
        name: '#6',
        sku: 'SKU004',
        category: '-',
        stock: 200,
        price: '$15.00',
        status: 'Published',
        added: '2024-03-10',
        image: 'path_to_product_image3',
        variants: ['Variant 2', 'Variant 3']
    },
    {
        id: 7,
        name: '#7',
        sku: 'SKU004',
        category: '-',
        stock: 200,
        price: '$15.00',
        status: 'Draft',
        added: '2024-03-10',
        image: 'path_to_product_image3',
        variants: ['Variant 2', 'Variant 3']
    },
    {
        id: 8,
        name: '#8',
        sku: 'SKU004',
        category: '-',
        stock: 200,
        price: '$15.00',
        status: 'Published',
        added: '2024-03-10',
        image: 'path_to_product_image3',
        variants: ['Variant 2', 'Variant 3']
    },
    {
        id: 9,
        name: '#9',
        sku: 'SKU004',
        category: '-',
        stock: 200,
        price: '$15.00',
        status: 'Draft',
        added: '2024-03-10',
        image: 'path_to_product_image3',
        variants: ['Variant 2', 'Variant 3']
    },
    {
        id: 10,
        name: '#10',
        sku: 'SKU004',
        category: '-',
        stock: 200,
        price: '$15.00',
        status: 'Draft',
        added: '2024-03-10',
        image: 'path_to_product_image3',
        variants: ['Variant 2', 'Variant 3']
    },
    {
        id: 11,
        name: '#11',
        sku: 'SKU004',
        category: '-',
        stock: 200,
        price: '$15.00',
        status: 'Draft',
        added: '2024-03-10',
        image: 'path_to_product_image3',
        variants: ['Variant 2', 'Variant 3']
    },
   
];
